include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - "**/build/**"
    - "**/generated_*.dart"
    - "**/*.g.dart"
    - "**/l10n*.dart"
    - "**/*.gen.dart"
    - "**/*.gr.dart"

linter:
  rules:
    flutter_style_todos: false
    prefer_relative_imports: true
